version: "3"

services:
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGE
      - MYSQL_DATABASE=change_me
      - MYSQL_USER=change_me
      - MYSQL_PASSWORD=change_me

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    depends_on:
      - db
    ports:
      - '6000:6000'
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=change_me
      - MYSQL_USER=change_me
      - MYSQL_PASS=change_me

  app:
    build:
      context: .
      dockerfile: application/Dockerfile
    depends_on:
      - db
    ports:
      - '5000:5000'
    environment:
      - APP_SECRET=CHANGE
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=change_me
      - MYSQL_USER=change_me
      - MYSQL_PASS=change_me

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090

volumes:
  db_data:
  prometheus_data: