version: "3.1"

services:
  scraper:
    # build:
    #   context: .
    #   dockerfile: ../scraper
    image: localhost:5000/skivrige/scraper

  frontend:
    # build:
    #   context: .
    #   dockerfile: ../frontend
    image: localhost:5000/skivrige/frontend

  backend:
    # build:
    #   context: .
    #   dockerfile: ../backend
    image: localhost:5000/skivrige/backend
  
  mongodb:
    image: mongo:3.6
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: localhost:5000/skivrige/nginx
    deploy:
      restart_policy:
        condition: on-failure
    ports: 
      - '80:80'
      - '443:443'