version: "3.1"

services:
  scraper:
    image: localhost:5000/skivrige/scraper
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    image: localhost:5000/skivrige/frontend
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    image: localhost:5000/skivrige/backend
    deploy:
      restart_policy:
        condition: on-failure
  
  mongodb:
    image: mongo:3.6
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: localhost:5000/skivrige/nginx
    deploy:
      restart_policy:
        condition: on-failure
    ports: 
      - '8080:80'